e strict';
var AWS=require('aws-sdk');
var dclient =new AWS.DynamoDB.DocumentClient();

/*
 * var input={
 *     TableName:"Bicycle",
 *          Key:{
 *                  "GTIN":"4bfae518-813a-11e8-8af9-07d7321fb577"
 *                       }
 *                       }
 *                       */

var getDateWarranty = (event, context, callback) => {
	    // TODO implement
	//     //callback(null, 'Hello from Lambada');
	//         
	//             var params={    
	//                 "TableName":"Bicycle",
	//                      "Key":{
	//                              "bicycleId":event.bicycleId
	//                                   }
	//                                       };
	//                                           
	//                                               
	//                                                   //el parametro event.params, trae lo que venga en el llamado de la funcion
	//                                                       dclient.get(params,(error,data)=>{
	//                                                               
	//                                                                     if(error){
	//                                                                              console.log(error) ;
	//                                                                                       callback(null,"error explodes" );
	//                                                                                             }else{
	//                                                                                                      //callback(null,data);
	//                                                                                                               //console.log(data.Item)
	//                                                                                                                       // console.log(data);
	//                                                                                                                                if(data!='{}'){
	//                                                                                                                                             var codigoRespuesta=-1; 
	//                                                                                                                                                          
	//                                                                                                                                                                       console.log("data item: "+data.Item.saleDate);
	//                                                                                                                                                                                    console.log("fecha hoy: "+hoyFecha());
	//                                                                                                                                                                                                 var fechaHoy = Date.parse(hoyFecha());
	//                                                                                                                                                                                                              var fechaGarantia = Date.parse(data.Item.saleDate);
	//
	//                                                                                                                                                                                                                           if (fechaHoy<fechaGarantia) {
	//                                                                                                                                                                                                                                           codigoRespuesta=0;//:0 es todo ok
	//                                                                                                                                                                                                                                                        }else   if (fechaHoy==fechaGarantia) {
	//                                                                                                                                                                                                                                                                        codigoRespuesta=1;//1:la garantia vence hoy
	//                                                                                                                                                                                                                                                                                     } else if (fechaHoy>fechaGarantia) {
	//                                                                                                                                                                                                                                                                                                     codigoRespuesta=2;//2:la garantia expiro 
	//                                                                                                                                                                                                                                                                                                                  }
	//                                                                                                                                                                                                                                                                                                                   
	//                                                                                                                                                                                                                                                                                                                                var articulo=(JSON.stringify(data.Item));
	//                                                                                                                                                                                                                                                                                                                                             //console.log(articulo);
	//                                                                                                                                                                                                                                                                                                                                                           //agregando nuevo atributo a la estructura del item en tiempo real 
	//                                                                                                                                                                                                                                                                                                                                                                        articulo= JSON.parse(articulo.replace("}",(',"codigoRespuesta":'+codigoRespuesta+"}")));
	//                                                                                                                                                                                                                                                                                                                                                                                      //console.log(articulo);
	//                                                                                                                                                                                                                                                                                                                                                                                                    callback(null,articulo);
	//                                                                                                                                                                                                                                                                                                                                                                                                             }else{
	//                                                                                                                                                                                                                                                                                                                                                                                                                          console.log("-100")
	//                                                                                                                                                                                                                                                                                                                                                                                                                                   }
	//                                                                                                                                                                                                                                                                                                                                                                                                                                            
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
	//
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                      };
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                      exports.getDateWarranty=getDateWarranty;
	//
	//
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                      function hoyFecha(){
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                          var hoy = new Date();
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                  var dd = hoy.getDate();
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                          var mm = hoy.getMonth()+1;
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  var yyyy = hoy.getFullYear();
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  dd = addZero(dd);
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          mm = addZero(mm);
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return yyyy+'-'+mm+'-'+dd;
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
	//
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   function addZero(i) {
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (i < 10) {
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               i = '0' + i;
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return i;
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
